[tool.poetry]
name = "pluginschema"
version = "0.1.0"
description = ""
authors = ["andre-cintra <andre.cintra@zup.com.br>"]

[tool.poetry.dependencies]
python = ">=3.10,<3.11"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"